/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.laboratorio2acinto;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author DELL
 */
public class MantenimientoUsuarios extends javax.swing.JDialog {
    // Definimos el modelo de la tabla
    DefaultTableModel modelo; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName());
    
    public MantenimientoUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    initComponents();
    
    // 1. Conectamos la tabla al modelo global
    jTable_Usuarios.setModel(DatosGlobales.modeloGlobal);
    
    // 2. APLICAMOS LA SEGURIDAD: 
    // La columna 4 es la contraseña. Le asignamos nuestro PasswordRenderer.
    jTable_Usuarios.getColumnModel().getColumn(4).setCellRenderer(new PasswordRenderer());
    }
    

    /**
     * Creates new form MantenimientoUsuarios
     */
    /*public MantenimientoUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Usuario = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Puesto = new javax.swing.JLabel();
        jText_Usuario = new javax.swing.JTextField();
        jText_Nombre = new javax.swing.JTextField();
        jText_Puesto = new javax.swing.JTextField();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jButton_Inactivar = new javax.swing.JButton();
        jButton_Limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Usuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel_Usuario.setText("Usuario");

        jLabel_Nombre.setText("Puesto");

        jLabel_Puesto.setText("Nombre");

        jText_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_UsuarioKeyTyped(evt);
            }
        });

        jText_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_NombreKeyTyped(evt);
            }
        });

        jText_Puesto.addActionListener(this::jText_PuestoActionPerformed);
        jText_Puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_PuestoKeyTyped(evt);
            }
        });

        jButton_Agregar.setText("Agregar");
        jButton_Agregar.setToolTipText("Presiona para agregar un usuario.");
        jButton_Agregar.addActionListener(this::jButton_AgregarActionPerformed);

        jButton_Modificar.setText("Modificar");
        jButton_Modificar.setToolTipText("Presiona para modificar un usuario, puedes cambiar nombre, puesto y estado.");
        jButton_Modificar.addActionListener(this::jButton_ModificarActionPerformed);

        jButton_Inactivar.setText("Inactivar");
        jButton_Inactivar.setToolTipText("Inactivar usuarios");
        jButton_Inactivar.addActionListener(this::jButton_InactivarActionPerformed);

        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.setToolTipText("Limpiar campos usuario, nombre y puesto.");
        jButton_Limpiar.addActionListener(this::jButton_LimpiarActionPerformed);

        jTable_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Usuarios);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mantenimiento de Usuarios");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        cbEstado.setEnabled(false);

        jLabel5.setText("Estado");

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(this::jButton_SalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Puesto)
                            .addComponent(jText_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Agregar)
                        .addGap(24, 24, 24)
                        .addComponent(jButton_Modificar)
                        .addGap(27, 27, 27)
                        .addComponent(jButton_Inactivar)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Limpiar))
                    .addComponent(jLabel4))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Salir)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Usuario)
                    .addComponent(jLabel_Puesto)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Agregar)
                    .addComponent(jButton_Inactivar)
                    .addComponent(jButton_Modificar)
                    .addComponent(jButton_Limpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Salir)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarActionPerformed
    String idNuevo = jText_Usuario.getText();
    boolean existe = false;

    // 1. Validar campos vacíos
    if (idNuevo.isEmpty() || jText_Nombre.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar los campos obligatorios");
        return; // Salimos del método para no seguir
    }

    // 2. RECORRIDO DE VALIDACIÓN: Buscamos en toda la tabla
    for (int i = 0; i < jTable_Usuarios.getRowCount(); i++) {
        // Comparamos el ID nuevo con el que ya está en la fila 'i', columna 0
        if (jTable_Usuarios.getValueAt(i, 0).toString().equals(idNuevo)) {
            existe = true;
            break; // Si lo encontramos, dejamos de buscar
        }
    }

    // 3. Decisión final
    if (existe) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El usuario con ID " + idNuevo + " ya existe.");
    } else {
        // Si no existe, lo agregamos normalmente
        String[] datos = {idNuevo, jText_Nombre.getText(), jText_Puesto.getText(), "ACTIVO","12345"};
        //modelo.addRow(datos);
        DatosGlobales.modeloGlobal.addRow(datos);
        limpiarCampos();
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado con éxito");
    }
    }//GEN-LAST:event_jButton_AgregarActionPerformed

    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
    //Limpiar campos de entrada.
    jText_Usuario.setText("");
    jText_Nombre.setText("");
    jText_Puesto.setText("");
    jText_Usuario.requestFocus();   
    limpiarCampos();
    }//GEN-LAST:event_jButton_LimpiarActionPerformed

    private void jText_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_UsuarioKeyTyped
        // 1. Capturamos el caracter que el usuario presionó
    char c = evt.getKeyChar();
    
    // 2. Si es una letra minúscula, la convertimos a mayúscula
    if (Character.isLowerCase(c)) {
        evt.setKeyChar(Character.toUpperCase(c));
    }
    }//GEN-LAST:event_jText_UsuarioKeyTyped

    private void jText_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_NombreKeyTyped
        // 1. Capturamos el caracter que el usuario presionó
    char c = evt.getKeyChar();
    
    // 2. Si es una letra minúscula, la convertimos a mayúscula
    if (Character.isLowerCase(c)) {
        evt.setKeyChar(Character.toUpperCase(c));
    }
    }//GEN-LAST:event_jText_NombreKeyTyped

    private void jText_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_PuestoActionPerformed

    private void jText_PuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_PuestoKeyTyped
        // 1. Capturamos el caracter que el usuario presionó
    char c = evt.getKeyChar();
    
    // 2. Si es una letra minúscula, la convertimos a mayúscula
    if (Character.isLowerCase(c)) {
        evt.setKeyChar(Character.toUpperCase(c));
    }
    }//GEN-LAST:event_jText_PuestoKeyTyped

    private void jButton_InactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InactivarActionPerformed
    int filaSeleccionada = jTable_Usuarios.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        // 1. Obtenemos el estado actual de la columna 3
        String estadoActual = DatosGlobales.modeloGlobal.getValueAt(filaSeleccionada, 3).toString();
        
        // 2. Verificamos si ya es "INACTIVO"
        if (estadoActual.equalsIgnoreCase("INACTIVO")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El usuario ya se encuentra en estado INACTIVO.", 
                "Aviso", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Salimos del método para no hacer nada más
        }

        // 3. Si no estaba inactivo, procedemos a cambiarlo
        DatosGlobales.modeloGlobal.setValueAt("INACTIVO", filaSeleccionada, 3);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario inactivado con éxito");
        limpiarCampos();
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla");
    }
    }//GEN-LAST:event_jButton_InactivarActionPerformed

    private void jTable_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsuariosMouseClicked
      /* int fila = jTable_Usuarios.getSelectedRow();
    if (fila != -1) {
        // Pasamos ID, Nombre y Puesto a los campos de texto
        jText_Usuario.setText(jTable_Usuarios.getValueAt(fila, 0).toString());
        jText_Nombre.setText(jTable_Usuarios.getValueAt(fila, 1).toString());
        jText_Puesto.setText(jTable_Usuarios.getValueAt(fila, 2).toString());
        
        // Pasamos el estado al ComboBox
        String estado = jTable_Usuarios.getValueAt(fila, 3).toString();
        cbEstado.setSelectedItem(estado);
    } */
        int fila = jTable_Usuarios.getSelectedRow();
    if (fila >= 0) {
        // Pasamos los datos de la tabla a los campos de texto
        jText_Usuario.setText(jTable_Usuarios.getValueAt(fila, 0).toString());
        jText_Nombre.setText(jTable_Usuarios.getValueAt(fila, 1).toString());
        jText_Puesto.setText(jTable_Usuarios.getValueAt(fila, 2).toString());
        // El estado está en la columna 3
        cbEstado.setSelectedItem(jTable_Usuarios.getValueAt(fila, 3).toString());
        // ACTIVAMOS el combo de estado para que puedan modificarlo
        cbEstado.setEnabled(true);
        
        // Bloqueamos el código para que no lo cambien (el ID suele ser único)
        jText_Usuario.setEnabled(false);
    }
    }//GEN-LAST:event_jTable_UsuariosMouseClicked

    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
int filaSeleccionada = jTable_Usuarios.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        // 1. Obtenemos los nuevos datos de los campos
        String nuevoNombre = jText_Nombre.getText();
        String nuevoPuesto = jText_Puesto.getText();
        
        // CORRECCIÓN AQUÍ: Usamos get y convertimos a String
        String nuevoEstado = cbEstado.getSelectedItem().toString();
        
        // 2. Validamos que no estén vacíos
        if (nuevoNombre.isEmpty() || nuevoPuesto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos Nombre y Puesto no pueden estar vacíos");
            return;
        }

        // 3. Actualizamos el MODELO GLOBAL
        DatosGlobales.modeloGlobal.setValueAt(nuevoNombre, filaSeleccionada, 1);
        DatosGlobales.modeloGlobal.setValueAt(nuevoPuesto, filaSeleccionada, 2);
        DatosGlobales.modeloGlobal.setValueAt(nuevoEstado, filaSeleccionada, 3);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Datos actualizados correctamente");
        limpiarCampos();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione la fila que desea modificar");
    }
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // Cerramos y liberamos los recursos de la ventana actual
    this.dispose();
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MantenimientoUsuarios dialog = new MantenimientoUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
private void limpiarCampos() {
    jText_Usuario.setText("");
    jText_Nombre.setText("");
    jText_Puesto.setText("");
    // Volvemos a colocar el combo en ACTIVO por defecto
    cbEstado.setSelectedIndex(0); 
    
    // BLOQUEAMOS el combo de estado
    cbEstado.setEnabled(false);
    jText_Usuario.setEnabled(true); // Para que puedan escribir un código nuevo
    jText_Usuario.requestFocus();   // Para que el cursor aparezca ahí
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_Inactivar;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Puesto;
    private javax.swing.JLabel jLabel_Usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Usuarios;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_Puesto;
    private javax.swing.JTextField jText_Usuario;
    // End of variables declaration//GEN-END:variables

    class PasswordRenderer extends DefaultTableCellRenderer {
    @Override
    protected void setValue(Object value) {
        if (value == null) {
            setText("");
        } else {
            // Reemplazamos cada letra por un asterisco
            String str = value.toString();
            setText("*".repeat(str.length())); 
        }
    }
}
}
