/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laboratorio2acinto;

/**
 *
 * @author umg
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        // Maximiza la ventana en ambos sentidos (Horizontal y Vertical)
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Opciones = new javax.swing.JMenu();
        jMenu_Manto_User = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu_Reset_Pass = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu_Opciones.setText("Gestion");

        jMenu_Manto_User.setText("Mantenimiento de Usuarios");
        jMenu_Manto_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Manto_UserActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenu_Manto_User);
        jMenu_Opciones.add(jSeparator1);

        jMenu_Reset_Pass.setText("Reincio de Clave");
        jMenu_Reset_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Reset_PassActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenu_Reset_Pass);
        jMenu_Opciones.add(jSeparator2);

        jMenu_Salir.setText("Salir");
        jMenu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SalirActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenu_Salir);

        jMenuBar1.add(jMenu_Opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SalirActionPerformed
        // 1. Preguntar al usuario si realmente desea cerrar sesión
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea cerrar sesión?", 
            "Cerrar Sesión", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);
            
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Creamos la instancia de la pantalla de Login
        Logging pantallaLogin = new Logging();
        
        // 3. La hacemos visible
        pantallaLogin.setVisible(true);
        pantallaLogin.setLocationRelativeTo(null); // Centrarla
        
        // 4. Cerramos (destruimos) la ventana de Menú actual
        this.dispose();
    }
    }//GEN-LAST:event_jMenu_SalirActionPerformed

    private void jMenu_Manto_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Manto_UserActionPerformed
        // 1. Creamos el objeto de la ventana. 
    // 'this' significa que este Menú es el dueño del diálogo.
    // 'true' significa que es modal (bloquea el menú hasta cerrar).
    MantenimientoUsuarios ventanaManto = new MantenimientoUsuarios(this, true);
    
    // 2. Centrar la ventanita respecto al menú
    ventanaManto.setLocationRelativeTo(this);
    
    // 3. Hacerla visible
    ventanaManto.setVisible(true);
    }//GEN-LAST:event_jMenu_Manto_UserActionPerformed

    private void jMenu_Reset_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Reset_PassActionPerformed
        // Creamos el objeto de la ventana
    // 'this' es el JFrame (Menu), 'true' la hace modal
    ReinicioClave ventana = new ReinicioClave(this, true);
    
    // La centramos respecto al menú
    ventana.setLocationRelativeTo(this);
    
    // La hacemos aparecer
    ventana.setVisible(true);
    }//GEN-LAST:event_jMenu_Reset_PassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenu_Manto_User;
    private javax.swing.JMenu jMenu_Opciones;
    private javax.swing.JMenuItem jMenu_Reset_Pass;
    private javax.swing.JMenuItem jMenu_Salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
