/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.laboratorio2acinto;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author DELL
 */
public class ReinicioClave extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReinicioClave.class.getName());

    /**
     * Creates new form ReinicioClave
     */
    public ReinicioClave(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    jTable_UsuariosClave.setModel(DatosGlobales.modeloGlobal);
    
    // APLICAR MÁSCARA: La contraseña es la columna 4
    jTable_UsuariosClave.getColumnModel().getColumn(4).setCellRenderer(new PasswordRenderer());
    
    jLabel_Mensaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_SeleccionUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_UsuariosClave = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPass_NewPass = new javax.swing.JPasswordField();
        jPass_NewPassConf = new javax.swing.JPasswordField();
        jLabel_ConfirmarPass = new javax.swing.JLabel();
        jButton_Update = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_Mensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reiniciar Contraseña");
        setModal(true);

        jLabel_SeleccionUsuario.setText("Selecciona Usuario:");

        jTable_UsuariosClave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_UsuariosClave);

        jLabel1.setText("Nueva Contraseña:");

        jLabel_ConfirmarPass.setText("Confirmar Contraseña:");

        jButton_Update.setText("Actualizar");
        jButton_Update.setToolTipText("Actualizar contraseña");
        jButton_Update.addActionListener(this::jButton_UpdateActionPerformed);

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.setToolTipText("Cancelar cambio de contraseña!");
        jButton_Cancelar.addActionListener(this::jButton_CancelarActionPerformed);

        jLabel_Mensaje.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Reinicio de Contraseñas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_SeleccionUsuario)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel_ConfirmarPass))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel_Mensaje)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPass_NewPassConf)
                                    .addComponent(jPass_NewPass)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jButton_Update)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel_SeleccionUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPass_NewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPass_NewPassConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ConfirmarPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Cancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
    int fila = jTable_UsuariosClave.getSelectedRow();
    
    // 1. Verificar selección
    if (fila == -1) {
        jLabel_Mensaje.setText("Seleccione un usuario de la tabla.");
        jLabel_Mensaje.setForeground(java.awt.Color.RED);
        return;
    }

    // 2. Obtener textos de los JPasswordField
    String pass1 = new String(jPass_NewPass.getPassword());
    String pass2 = new String(jPass_NewPassConf.getPassword());

    // 3. Validar que coincidan
    if (!pass1.equals(pass2)) {
        jLabel_Mensaje.setText("Las contraseñas no coinciden.");
        jLabel_Mensaje.setForeground(java.awt.Color.RED);
        return;
    }

    // 4. Validar complejidad y longitud
    if (!validarComplejidad(pass1)) {
        jLabel_Mensaje.setText("Debe tener +12 caracteres, Mayús, Minús y Núm.");
        jLabel_Mensaje.setForeground(java.awt.Color.RED);
        return;
    }

    // 5. Si todo está OK, actualizamos el modelo global
    // Recuerda: la columna 4 es donde guardamos el password
    DatosGlobales.modeloGlobal.setValueAt(pass1, fila, 4);
    
    // Limpieza y éxito
    jLabel_Mensaje.setText("¡Contraseña actualizada con éxito!");
    jLabel_Mensaje.setForeground(new java.awt.Color(0, 153, 0)); // Color verde
    jPass_NewPass.setText("");
    jPass_NewPassConf.setText("");
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Desea cancelar el reinicio de contraseña?", 
            "Confirmar", 
            javax.swing.JOptionPane.YES_NO_OPTION);
            
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
    }
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReinicioClave dialog = new ReinicioClave(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_ConfirmarPass;
    private javax.swing.JLabel jLabel_Mensaje;
    private javax.swing.JLabel jLabel_SeleccionUsuario;
    private javax.swing.JPasswordField jPass_NewPass;
    private javax.swing.JPasswordField jPass_NewPassConf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_UsuariosClave;
    // End of variables declaration//GEN-END:variables

    private boolean validarComplejidad(String pass) {
    // Mínimo 12 caracteres, una mayúscula, una minúscula y un número
    String regex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{12,}$";
    return pass.matches(regex);
}
    class PasswordRenderer extends DefaultTableCellRenderer {
    @Override
    protected void setValue(Object value) {
        if (value == null) {
            setText("");
        } else {
            // Reemplazamos cada letra por un asterisco
            String str = value.toString();
            setText("*".repeat(str.length())); 
        }
    }
}
}
